// <auto-generated />
using System;
using ApiWatch.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiWatch.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421183537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiWatch.Core.Entities.CheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsUp")
                        .HasColumnType("boolean");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MonitoredEndpointId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAt");

                    b.HasIndex("MonitoredEndpointId");

                    b.ToTable("CheckResults");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MonitoredEndpointId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredEndpointId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.MonitoredEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Url");

                    b.ToTable("MonitoredEndpoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 4, 21, 18, 35, 36, 941, DateTimeKind.Utc).AddTicks(5536),
                            IntervalSeconds = 60,
                            IsActive = true,
                            Name = "Google",
                            TimeoutSeconds = 10,
                            Url = "https://www.google.com"
                        });
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.CheckResult", b =>
                {
                    b.HasOne("ApiWatch.Core.Entities.MonitoredEndpoint", "MonitoredEndpoint")
                        .WithMany("CheckResults")
                        .HasForeignKey("MonitoredEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredEndpoint");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.Incident", b =>
                {
                    b.HasOne("ApiWatch.Core.Entities.MonitoredEndpoint", "MonitoredEndpoint")
                        .WithMany()
                        .HasForeignKey("MonitoredEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredEndpoint");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.MonitoredEndpoint", b =>
                {
                    b.Navigation("CheckResults");
                });
#pragma warning restore 612, 618
        }
    }
}
