// <auto-generated />
using System;
using ApiWatch.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiWatch.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422104612_AddSubscriptions")]
    partial class AddSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiWatch.Core.Entities.CheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsUp")
                        .HasColumnType("boolean");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MonitoredEndpointId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAt");

                    b.HasIndex("MonitoredEndpointId");

                    b.ToTable("CheckResults");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MonitoredEndpointId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredEndpointId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.MonitoredEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Url");

                    b.HasIndex("UserId");

                    b.ToTable("MonitoredEndpoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 4, 22, 10, 46, 12, 369, DateTimeKind.Utc).AddTicks(3071),
                            IntervalSeconds = 60,
                            IsActive = true,
                            Name = "Google",
                            TimeoutSeconds = 10,
                            Url = "https://www.google.com"
                        });
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasEmailAlerts")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasStatusPage")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWebhooks")
                        .HasColumnType("boolean");

                    b.Property<int>("HistoryDays")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEndpoints")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTeamMembers")
                        .HasColumnType("integer");

                    b.Property<int>("MinIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PriceMonthly")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasEmailAlerts = false,
                            HasStatusPage = false,
                            HasWebhooks = false,
                            HistoryDays = 7,
                            MaxEndpoints = 3,
                            MaxTeamMembers = 1,
                            MinIntervalSeconds = 300,
                            Name = "Free",
                            PriceMonthly = 0m
                        },
                        new
                        {
                            Id = 2,
                            HasEmailAlerts = true,
                            HasStatusPage = false,
                            HasWebhooks = false,
                            HistoryDays = 30,
                            MaxEndpoints = 15,
                            MaxTeamMembers = 1,
                            MinIntervalSeconds = 60,
                            Name = "Starter",
                            PriceMonthly = 12m
                        },
                        new
                        {
                            Id = 3,
                            HasEmailAlerts = true,
                            HasStatusPage = true,
                            HasWebhooks = true,
                            HistoryDays = 90,
                            MaxEndpoints = 50,
                            MaxTeamMembers = 3,
                            MinIntervalSeconds = 30,
                            Name = "Pro",
                            PriceMonthly = 39m
                        },
                        new
                        {
                            Id = 4,
                            HasEmailAlerts = true,
                            HasStatusPage = true,
                            HasWebhooks = true,
                            HistoryDays = 365,
                            MaxEndpoints = -1,
                            MaxTeamMembers = 10,
                            MinIntervalSeconds = 30,
                            Name = "Business",
                            PriceMonthly = 89m
                        });
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.CheckResult", b =>
                {
                    b.HasOne("ApiWatch.Core.Entities.MonitoredEndpoint", "MonitoredEndpoint")
                        .WithMany("CheckResults")
                        .HasForeignKey("MonitoredEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredEndpoint");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.Incident", b =>
                {
                    b.HasOne("ApiWatch.Core.Entities.MonitoredEndpoint", "MonitoredEndpoint")
                        .WithMany()
                        .HasForeignKey("MonitoredEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredEndpoint");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.MonitoredEndpoint", b =>
                {
                    b.HasOne("ApiWatch.Core.Entities.User", "User")
                        .WithMany("Endpoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.Subscription", b =>
                {
                    b.HasOne("ApiWatch.Core.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiWatch.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.User", b =>
                {
                    b.HasOne("ApiWatch.Core.Entities.Plan", "Plan")
                        .WithMany("Users")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.MonitoredEndpoint", b =>
                {
                    b.Navigation("CheckResults");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.Plan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApiWatch.Core.Entities.User", b =>
                {
                    b.Navigation("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
